logging:
    level:
        org:
            springframework:
                boot:
                    autoconfigure: ERROR
server:
    port: 8081
springdoc:
    swagger-ui:
        path: /swagger-ui.html
